<ul id="menu" class="page-sidebar-menu">
    <li {!! (Request::is('admin') ? 'class="active"' : '') !!}>
        <a href="{{ url('admin') }}">
            <i class="livicon" data-name="home" data-size="18" data-c="#418BCA" data-hc="#418BCA"
               data-loop="true"></i>
            <span class="title">Dashboard</span>
        </a>
    </li>


    <li {!! (Request::is('admin/curriculamvitae') || Request::is('admin/curriculamvitae/add') || Request::is('admin/curriculamvitae/connect') || Request::is('admin/curriculamvitae/completed') || Request::is('admin/curriculamvitae/canceled') ? 'class="active"' : '') !!}>
        <a href="#">
            <i class="livicon" data-name="gear" data-size="18" data-c="#6CC66C" data-hc="#6CC66C"
               data-loop="true"></i>
            <span class="title">Curriculam Vitae</span>
            <span class="fa arrow"></span>
        </a>
        <ul class="sub-menu">
            <li {!! (Request::is('admin/curriculamvitae') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('admin/curriculamvitae') }}">
                    <i class="fa fa-angle-double-right"></i>
                    Curriculams
                </a>
            </li>
            <li {!! (Request::is('admin/curriculamvitae/add') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('admin/curriculamvitae/add') }}">
                    <i class="fa fa-angle-double-right"></i>
                    Add
                </a>
            </li>
            <li {!! (Request::is('admin/curriculamvitae/connect') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('admin/curriculamvitae/connect') }}">
                    <i class="fa fa-angle-double-right"></i>
                    New Requests
                </a>
            </li>
            <li {!! (Request::is('admin/curriculamvitae/completed') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('admin/curriculamvitae/completed') }}">
                    <i class="fa fa-angle-double-right"></i>
                    Completed Requests
                </a>
            </li>
            <li {!! (Request::is('admin/curriculamvitae/canceled') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('admin/curriculamvitae/canceled') }}">
                    <i class="fa fa-angle-double-right"></i>
                    Canceled Requests
                </a>
            </li>
        </ul>
    </li>

    <!-- Menus generated by CRUD generator -->
    @include('admin/layouts/menu')
</ul>
